# Generated by Django 6.0.3 on 2026-03-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_horas', models.PositiveIntegerField(default=4)),
                ('valor_onix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_spin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Passeio',
                'verbose_name_plural': 'Passeios',
                'ordering': ['nome'],
            },
        ),
    ]
