# Generated by Django 6.0.3 on 2026-03-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf'),
        ('motoristas', '0001_initial'),
        ('passeios', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('transfer_in', 'Transfer In (chegada)'), ('transfer_out', 'Transfer Out (saída)'), ('transfer_ida_volta', 'Transfer Ida + Volta'), ('city_tour', 'City Tour')], max_length=30)),
                ('data_hora', models.DateTimeField()),
                ('endereco_embarque', models.CharField(max_length=300)),
                ('destino', models.CharField(max_length=300)),
                ('codigo_voo', models.CharField(blank=True, max_length=20, null=True)),
                ('num_adultos', models.PositiveIntegerField(default=1)),
                ('num_adolescentes', models.PositiveIntegerField(default=0)),
                ('num_criancas', models.PositiveIntegerField(default=0)),
                ('malas_despachadas', models.PositiveIntegerField(default=0)),
                ('malas_mao', models.PositiveIntegerField(default=0)),
                ('reboque', models.BooleanField(default=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_sinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial (sinal pago)'), ('pago', 'Pago integralmente')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='clientes.cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='motoristas.motorista')),
                ('passeio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='passeios.passeio')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('adolescente', 'Adolescente'), ('crianca', 'Criança')], default='adulto', max_length=20)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='agendamentos.agendamento')),
            ],
            options={
                'verbose_name': 'Passageiro',
                'verbose_name_plural': 'Passageiros',
            },
        ),
    ]
