# Generated by Django 6.0.3 on 2026-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('cnh', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('proprio', 'Próprio F&F'), ('parceiro', 'Parceiro de Agência'), ('freelancer', 'Freelancer')], max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=150)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
